### ISSUE TITLE
Feature request: dark mode

### ISSUE THREAD

**Issue by mcstafford-git** [hydroxion/dailly#1]
Things look good, and for some of us could look better if the color scheme wasn't as bright as it is.

**Comment by mizzunet** [comment]
> Things look good, and for some of us could look better if the color scheme wasn't as bright as it is.

It's been already on @hydroxin's To-do
https://github.com/hydroxion/dailly/projects/1#card-61363244

**Comment by hydroxion** [comment]
The dark theme is now a priority in the road map. Please, keep track of its development at the [road map](https://github.com/hydroxion/dailly/projects/1#column-14365833).

I'll close the issue as soon as the feature is done.

Thanks for the issue.

**Comment by hydroxion** [comment]
The dark theme is now available.

If you have the application installed, please, open, close, and open again to receive the update.

The official release will be created today and in 3-4 days it'll be available in Play Store.
