### ISSUE TITLE
[FR]Ability to add tasks from Widget 

### ISSUE THREAD

**Issue by mizzunet** [hydroxion/dailly#2]
This request is regarding Widget To-do, https://github.com/hydroxion/dailly/projects/1#card-61364058.
Not just showing the list goals, but one more functionality to the widget that is adding new tasks.

**Comment by hydroxion** [comment]
What's up.

I added this note to the feature in the [road map](https://github.com/hydroxion/dailly/projects/1#column-14365832). It will take some time to implement this feature in special, once it requires the project to be ejected and integrated with native code, for the current features planned to be implemented (top-bottom) I'll keep using Expo, but once a good majority of the road map is done I'll start to work on the project ejection.

Thanks for the issue.

**Comment by mizzunet** [comment]
Great, thanks :)
